const os = require('os')

console.log(`Arquitectura: ${os.arch()}`)
console.log(`Constants: ${JSON.stringify(os.constants, null, 2)}`)
console.log(`CPUs: ${JSON.stringify(os.cpus(), null, 2)}`)
console.log(`Memoria Libre: ${os.freemem()}`)
console.log(`Home directory: ${os.homedir()}`)
console.log(`Hostname: ${os.hostname()}`)
console.log(`Interfaces de red: ${JSON.stringify(os.networkInterfaces(), null, 2)}`)
console.log(`Plataforma: ${os.platform()}`)
console.log(`Release: ${os.release()}`)
console.log(`Directorio temporal: ${os.tmpdir()}`)
console.log(`Memoria total: ${os.totalmem()}`)
console.log(`Tipo: ${os.type()}`)